version: "3"

services:
  db:
    image: mysql:latest
    container_name: Order_DB
    ports:
      - "33010:3306"
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: s3cr37
      MYSQL_DATABASE: order_db
